### ISSUE TITLE
Use the latest release of mydumper

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rpm-specs#2]
@slapula could you help switch to the latest release of mydumper from its [GH repo](https://github.com/maxbube/mydumper)? Thanks!

```
+URL:            https://github.com/maxbube/mydumper
+Source0:        https://github.com/maxbube/mydumper/archive/v%{version}.zip
```

**Comment by slapula** [comment]
this has been taken care of with the attached PR

**Comment by ronaldtse** [comment]
Thanks @slapula !
